[[IgnoredVulns]]
id = "GHSA-f8q6-p94x-37v3"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-mwcw-c2x4-8c55"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-76p7-773f-r4q5"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-9965-vmph-33xx"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-vghf-hv5q-vc2g"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-mh29-5h37-fv8m"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-73rr-hh4g-fpgx"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-xxjr-mmjv-4gpg"
reason = "Test dependency"

[[IgnoredVulns]]
id = "GHSA-6rw7-vpxm-498p"
reason = "Test dependency"